# .gitlab-ci.yml
image: node:9.11.1

# Docker images come with yarn preinstalled
before_script:
  - apt-get update -qq && apt-get install

# And to cache them as well.
cache:
  paths:
    - node_modules/
    - .yarn

# You specify the stages. Those are the steps that GitLab will go through
# Order matters.
stages:
  - build
  - test

Build:
  stage: build
  tags:
    - node
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run build:prod

Test:
  stage: test
  tags:
  - node
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
  # Installs Chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
  # Runs the tests.
    - yarn run test:ci
