version: 2
jobs:
  build:
    working_directory: ~/angular-remote-container
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: angular-remote-container-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: angular-remote-container-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Angular build
          command: yarn run build:prod
      - run:
          name: Angular Unit Test
          command: yarn run test:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports/junit/test-results.xml
      - run:
          name: Angular E2E Test
          command: yarn run e2e:ci
